### PR TITLE
implement unsubscribe from event

### PR DESCRIPTION
**Pull request by adrianosela**
closes https://github.com/adrianosela/mapp/issues/96

### CODE REVIEW

**Comment by adrianosela** [comment]
It unsubscribes from all the given event ids in the body `eventIds = req.body.eventIds;`

**Comment by adrianosela** [comment]
@chrisneuf

**Comment by chrisneuf** [comment]
Ok sounds good, I think we'll just send one at a time but it works

**Comment by adrianosela** [comment]
Yeah i would prefer if we did sub and unsub one event at a time... batch operations are bad because they are stateful, not very REST-like. But thats how the sub operation was implemented so i did it like this for consistency. I think we should change both... but this works. @israeltq @chrisneuf

**Pull request merged**
