### PR TITLE
Implemented Remove Pending Invitation

### PR DESCRIPTION
**Pull request by israeltq**

### CODE REVIEW

**Comment by israeltq** [comment]
> 
> 
> This should all be handled by accept or decline invite no?

This is the decline invite functionality

**Comment by adrianosela** [comment]
The right way to do this would be to have a 'respond invite' endpoint and handle both acceptance and decline in there. Also, the path name is very confusing the way you've done it (a put for /user/pending). should be a post for /user/declineInvite or something more descriptive than that.

**Comment by israeltq** [comment]
In theory yes we could handle both accept and decline, but the "accept" invite is basically subscribing to an event, which can be for people without needing to be invited to an event if its is public (which we still not handle yet). I think it's ok to have two separate calls in order to handle both public and non-public events on the same call. Regarding the call name, I will make it more clear

**Comment by israeltq** [comment]
I will create an issue to modify the calls that need to handle public and private events accordingly.

**Pull request merged**
